const mongoose = require("mongoose");

const requireLogin = require("../middlewares/requireLogin");
const requireCredits = require("../middlewares/requireCredits");
const Mailer = require("../services/Mailer");
const surveyTemplate = require("../services/emailTemplates/surveyTemplate");

const Survey = mongoose.model("surveys"); // some testing frameworks will complain if your require in a file multiple times so this is a workaround

module.exports = app => {
	app.get("/api/surveys/thanks", (req, res) => {
		res.send("Thanks for voting! I think it's time to hire Neil :)");
	});

	app.post("/api/surveys", requireLogin, requireCredits, async (req, res) => {
		const { title, subject, body, recipients } = req.body;

		const survey = new Survey({
			title,
			body,
			subject,
			recipients: recipients
				.split(",")
				.map(email => ({ email: email.trim() })), // identify returning an object with ({})
			_user: req.user.id, // user id that is automatically generated by mongo/mongoose
			dateSent: Date.now()
		});

		// send email
		const mailer = new Mailer(survey, surveyTemplate(survey));

		try {
			await mailer.send();
			await survey.save();
			req.user.credits -= 1;
			const user = await req.user.save();

			res.send(user);
		} catch (err) {
			res.status(422).send(err);
		}
	});
};
